### PR TITLE
Adds electric minecarts and overhead lines (WIP)

### PR DESCRIPTION
**Pull request by jrddunbr**
Having some issues with the connectivity of the cart as it goes along:

- [x] As it changes from wire segment to wire segment, it needs to disconnect from the original segment and attach to the new one.
- [x] If the cart is placed, it needs to attach to a wire if it's under one
- [x] If the cart is deleted, it needs to detach from the wire
- [x] If the cart moves out from under a wire, it needs to stop drawing power from the last wire it was under

I have some thoughts about controls via nearby OpenComputers blocks and/or Eln wireless signals, but haven't gotten around to that yet. Maybe the locomotive gets named if the user enters a GUI? IDK.

### CODE REVIEW

**Comment by jrddunbr** [comment]
I left a note in the code itself but the carts can't have MNA components in them. :/

**Comment by DarthSidiousPalpatine** [comment]
Do you need any models/textures, idk?

**Comment by jrddunbr** [comment]
The under-track power texture would be helpful. I want to make several of these that basically are a block with wires overlaid in a horizontal direction on the side of the block. It should look good when tiled hundreds of blocks.

Variants would be said wires embedded in colors/textures such as concrete, steel, brick, etc.

**Comment by DarthSidiousPalpatine** [comment]
So, i think I can make just a naked wire texture, so you'll be able to put it on side of a block near minecart or something?

**Comment by DarthSidiousPalpatine** [comment]
Or you can also put it ON a track, in a middle, so, maybe, it would be able to put it even on modded tracks?

**Comment by DarthSidiousPalpatine** [comment]
image
I mean, you can just put a regular but naked (texture will be better) wire on side or on a track.

**Comment by jrddunbr** [comment]
I'm talking about when the block is under the track. It's going to have a wire texture for the cabling that would be like the power wire, not the bus bar. The bus bar I'm going to use OpenGL calls and a orange version of the cable texture.

**Comment by jrddunbr** [comment]
(It also goes under the track; the idea is that it looks like there's cables run for it when the block is the support in a bridge)

**Comment by DarthSidiousPalpatine** [comment]
Well, i dont get it, sadly.
I can't google power wire or bus bar images related to railroading :/


Oh waaaait, you just need a undertrack block that looks like concrete with wires embeded, ok, ok)

**Comment by DarthSidiousPalpatine** [comment]
image

**Comment by jrddunbr** [comment]
Yep, that's the right idea. Although I probably only need the side textures not the cut away as it'll be the side cable texture on all sides (the cable ends would always be hidden by the adjacent blocks and never be exposed)

**Comment by DarthSidiousPalpatine** [comment]
image
ok

**Comment by DarthSidiousPalpatine** [comment]
texture
here it is, an overlay.

**Comment by jrddunbr** [comment]
So I determined that I need to rewrite the over and underground wire with an instance of SimpleNode instead of TransparentNode so that I have more control over the Minecraft block type. This would then allow me to change the type of block for the cable simple nodes to be able to be placed in the air like regular blocks would be able to, while also having them have no hitbox since they are right over the tracks.

I am still having some issues with the cart entities where they despawn on world close instead of being persistent. I have no idea why this is happening and so I'd need to go through the Minecart code some more.

Right now everything works with regards to the MNA however I will be making some changes that might break it again. I want to make it such that the catenaries are powered by the poles that they attach to via an isolated DC/DC transformer (with an optional 1:4 transformer in it for upping to 3.2kV). It needs to be isolated because the cables are updated _very_ frequently and it would cause massive MNA performance issues if the cables were not part of a Line optimization. I also intend to make a new cable mask to prevent connecting wires directly to the cables and forcing the use of an isolated transformer.

The catenary will connect to a Transparent Node Power Node at the top of the pole (similar to how the Grid Switch's power pole works) that allows for the special connection at the correct height. There will also be a ceiling/base mounted transformer that attaches directly to the catenary for use without the poles in more constricted build environments to allow for more creative flexibility.

**Comment by jrddunbr** [comment]
Oh, also, I intend to write an integration with OpenComputers/ComputerCraft that allows the cars to be controlled from a centralized point; this would allow speed control and position information. I also want to figure something out for routing these since I can't really integrate with Railcraft feasibly for this.

**Comment by jrddunbr** [comment]
Will need to rebase at a future date.

**Pull request closed without merging**
